name: Terraform Azure Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write
 

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks (secret scan)
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          output_format: sarif
          output_file_path: reports/results.sarif
          soft_fail: true # set to false once findings are triaged, to block on issues

      - name: Run Trivy vulnerability scanner (IaC)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: .
          exit-code: 0 # set to 1 once findings are triaged, to block on issues
          severity: CRITICAL,HIGH,MEDIUM
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      #- name: Terraform Plan
        #env:
          #TF_VAR_ssh_public_key: ${{ vars.SSH_PUBLIC_KEY }}
        #run: terraform plan -input=false #-out=tfplan

      #- name: Upload plan artifact
        #uses: actions/upload-artifact@v4
        #with:
          #name: tfplan
          #path: tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' #&& github.event_name == 'push'
        env:
          TF_VAR_ssh_public_key: ${{ vars.SSH_PUBLIC_KEY }}
        run: terraform apply -input=false -auto-approve #tfplan
